export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};

export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  ENABLE_CATEGORY_REQUEST: "ENABLE_CATEGORY_REQUEST",
  ENABLE_CATEGORY_FAILURE: "ENABLE_CATEGORY_FAILURE",
  ENABLE_CATEGORY_SUCCESS: "ENABLE_CATEGORY_SUCCESS",
};

export const notifyConstants = {
  GET_NOTIFY_REQUEST: "GET_NOTIFY_REQUEST",
  GET_NOTIFY_SUCCESS: "GET_NOTIFY_SUCCESS",
  GET_NOTIFY_FAILURE: "GET_NOTIFY_FAILURE",
  PUSH_NOTIFY: "PUSH_NOTIFY",
  READ_NOTIFY: "READ_NOTIFY",
};
export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_REQUEST: "ENABLE_PRODUCT_REQUEST",
  ENABLE_PRODUCT_SUCCESS: "ENABLE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_FAILURE: "ENABLE_PRODUCT_FAILURE",
};
export const initialDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",
};
export const pageConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
  CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
};

export const orderConstants = {
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",

  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_FAILURE: "UPDATE_ORDER_FAILURE",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",

  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
  GET_ORDER_DETAIL_FAILURE: "GET_ORDER_DETAIL_FAILURE",
};

export const labelConstants = {
  DELETE_LABEL_REQUEST: "DELETE_LABEL_REQUEST",
  DELETE_LABEL_SUCCESS: "DELETE_LABEL_SUCCESS",
  DELETE_LABEL_FAILURE: "DELETE_LABEL_FAILURE",

  CREATE_LABEL_REQUEST: "CREATE_LABEL_REQUEST",
  CREATE_LABEL_SUCCESS: "CREATE_LABEL_SUCCESS",
  CREATE_LABEL_FAILURE: "CREATE_LABEL_FAILURE",

  GET_ALL_LABEL_REQUEST: "GET_ALL_LABEL_REQUEST",
  GET_ALL_LABEL_FAILURE: "GET_ALL_LABEL_FAILURE",
  GET_ALL_LABEL_SUCCESS: "GET_ALL_LABEL_SUCCESS",

  GET_LABEL_REQUEST: "GET_LABEL_REQUEST",
  GET_LABEL_FAILURE: "GET_LABEL_FAILURE",
  GET_LABEL_SUCCESS: "GET_LABEL_SUCCESS",

  UPDATE_LABEL_REQUEST: "UPDATE_LABEL_REQUEST",
  UPDATE_LABEL_FAILURE: "UPDATE_LABEL_FAILURE",
  UPDATE_LABEL_SUCCESS: "UPDATE_LABEL_SUCCESS",

  GET_LABEL_DETAIL_REQUEST: "GET_LABEL_DETAIL_REQUEST",
  GET_LABEL_DETAIL_SUCCESS: "GET_LABEL_DETAIL_SUCCESS",
  GET_LABEL_DETAIL_FAILURE: "GET_LABEL_DETAIL_FAILURE",
};

export const statisticConstants = {
  GET_STATISTIC_SUCCESS: "GET_STATISTIC_SUCCESS",
  GET_getTotalOrderPricePerMonthByYear_SUCCESS:
    "GET_getTotalOrderPricePerMonthByYear_SUCCESS",
};
